name: Pipeline Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3

      - name: Python configuration
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'